# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

#theme                    :  minimal-mistakes-jekyll
remote_theme              : "mmistakes/minimal-mistakes"

minimal_mistakes_skin    : "default" # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
#
# GENERAL
#
# Site Settings
locale                   : "en-US"
title                    : "Cronofear Softworks"
title_separator          : "-"
name                     : &name "Kevin Yabar G." # &name is a YAML anchor which can be *referenced later
description              : &description "Games and Tools development in Unreal Engine 4."
url                      : https://cronofeargameworks.github.io # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : #the subpath of your site, e.g. "/blog" "/home"
repository               : "CronofearSoftworks/website"
#head_scripts             :
#  - https://code.jquery.com/jquery-3.2.1.min.js
#footer_scripts            :
#  -
#
# POSTS
#
teaser                   : "/assets/images/500x300.png" # path of fallback teaser image, e.g. Default image for posts
# breadcrumbs            : false # true, false (default)
words_per_minute         : 200
comments:
  provider               : "staticman_v2" # false (default), "disqus", "discourse", "facebook", "google-plus", "staticman_v2", "staticman" "custom"
  disqus:
    shortname            :
  discourse:
    server               : # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
  facebook:
    # https://developers.facebook.com/docs/plugins/comments
    appid                :
    num_posts            : # 5 (default)
    colorscheme          : # "light" (default), "dark"
staticman:
  allowedFields          : # ['name', 'email', 'url', 'message']
  branch                 : "master"
  commitMessage          : # "New comment"
  filename               : # comment-{@timestamp}
  format                 : # "yml"
  moderation             : # true
  path                   : # "_data/comments/{options.slug}"
  requiredFields         : # ['name', 'email', 'message']
  transforms:
    email                : # "md5"
  generatedFields:
    date:
      type               : # "date"
      options:
        format           : # "iso8601" (default), "timestamp-seconds", "timestamp-milliseconds"
reCaptcha:
  siteKey                : "6LdRBykTAAAAAFB46MnIu6ixuxwu9W1ihFF8G60Q"
  secret                 : "PznnZGu3P6eTHRPLORniSq+J61YEf+A9zmColXDM5icqF49gbunH51B8+h+i2IvewpuxtA9TFoK68TuhUp/X3YKmmqhXasegHYabY50fqF9nJh9npWNhvITdkQHeaOqnFXUIwxfiEeUt49Yoa2waRR7a5LdRAP3SVM8hz0KIBT4="


#
# SEO Related
#
atom_feed:
  path                   : # blank (default) uses feed.xml
search                   : true # true, false (default)

google_site_verification : "UQj93ERU9zgECodaaXgVpkjrFn9UrDMEzVamacSoQ8Y" # Replace this with your ID, or delete
bing_site_verification   :
yandex_site_verification :
naver_site_verification  :
#
# Social Sharing
#
twitter:
  username               : &twitter "CronofearSW"
facebook:
  username               : &facebook "Cronofear"
  app_id                 : "Cronofear"
  publisher              :
og_image                 : "/assets/images/core/logo_full.png" # Open Graph/Twitter default site image, OVERRIDE WITH header.image
# For specifying social profiles, used in _includes/seo.html
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles
    - "https://twitter.com/CronofearSW"
    - "https://facebook.com/cronofear"
    - "https://www.youtube.com/channel/UCTE-TAOV8uGyX5ITofi93Ew"
    - "https://www.tumblr.com/blog/cronofearsoftworks"
    - "https://www.unrealengine.com/marketplace/profile/Cronofear%20Softworks"

#
# Analytics
#
analytics:
  provider               : "google-universal" # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          : "UA-2011187-3" # Replace this with your ID, or delete

#
# Site Author (ABOUT)
#
author:
  name             : *name # *name is a YAML reference pointing to the &anchor earlier
  avatar           : "/assets/images/core/avatar.jpg"
  bio              : "Indie Game developer. Coffee to code converter bio-machine. Bug hunter."
  location         : "Peru"
  email            : "cronofearsoftworks@gmail.com"
  uri              : "https://cronofeargameworks.github.io"
  bitbucket        : 
  codepen          :
  dribbble         :
  flickr           :
  facebook         : *facebook
  foursquare       :
  github           : "CronofearSoftworks"
  gitlab           :
  google_plus      :
  keybase          :
  instagram        : 
  lastfm           :
  linkedin         :
  pinterest        :
  soundcloud       :
  stackoverflow    : # https://stackoverflow.com/users/123456/username
  steam            :
  tumblr           : "cronofearsoftworks"
  twitter          : *twitter
  vine             :
  weibo            :
  xing             :
  youtube          : "UCTE-TAOV8uGyX5ITofi93Ew"


# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - .travis.yml
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

#
# Defaults configurations for files per folder
#
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      read_time: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _games
  - scope:
      path: "_games"
      type: games
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  # _gameassets
  - scope:
      path: "_gameassets"
      type: gameassets
    values:
      layout: single
      author_profile: true
      share: true
      comment: true
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: false
      share: true
  # _docs-save-load-system
  - scope:
      path: "_docs-save-load-system"
      type: docs-save-load-system
    values:
      layout: single
      read_time: false
      author_profile: false
      share: false
      comments: false
      sidebar:
        nav: "docs-save-load-system"
  # _docs-level-makr-kit
  - scope:
      path: "_docs-level-makr-kit"
      type: docs-level-makr-kit
    values:
      layout: single
      read_time: false
      author_profile: false
      share: false
      comments: false
      sidebar:
        nav: "docs-level-makr-kit"
#
# Collections, useful for creating stuff that can be showed as a list/array (games, portfolio, assets)
#
collections:
  games:
    output: true
    permalink: /:collection/:path/
  gameassets:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  docs-save-load-system:
    output: true
    permalink: /:collection/:path/
  docs-level-makr-kit:
    output: true
    permalink: /:collection/:path/

# Outputting
permalink: /:categories/:title/
# paginate: 5 # amount of posts to show
# paginate_path: /page:num/
timezone: America/New_York # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

#
# PAGINATION CAN BE ENABLED TO SHOW ONLY N POSTS IN ONE PLACE: 
#
# paginate: 5 # jekyll-paginate NEED TO BE ENABLED

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-remote-theme

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - vendor
# - jekyll-remote-theme


# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/


# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development
